name: docx_template
description: A Docx template engine.
version: 0.4.0
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  xml: ^6.5.0
  collection: ^1.19.0
  path: ^1.9.1
dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
